### ISSUE TITLE
hey I have issue please give me suggestion

### ISSUE THREAD

**Issue by its-me-yasho** [its-me-yasho/justforfun#9]
### **this issue is to add your best friends** 

*information about issue*

![joshua-sortino-LqKhnDzSF-8-unsplash](https://user-images.githubusercontent.com/68093591/115960434-0e7c3880-a52f-11eb-8ad0-427c41e15700.jpg)

- **issue 1**
   - subissue 1.1

1. issue 1
2. issue 2

[this is my git hub profile](https://github.com/its-me-yasho)

> my name is yashodhan

> my repo issue

```
abstract class Demo2 extends Demo1
{
	final void m1()
	{
		System.out.println("m1 method");
	}
	
	void m2()
	{
		System.out.println("m2 method");
	}
}
```

- [cat]
- [dog]

@its-me-yasho

**Comment by its-me-sanjay** [comment]
**thanks for giving me suggestion @its-me-sanjay 
can u send me pull request then I can merge your changes **

**Comment by its-me-yasho** [comment]
**thanks for giving me suggestion @its-me-sanjay
can u send me pull request then I can merge your changes **
